<!DOCTYPE html>
<html>
<head>
  <title>Server Malfunction Rate Calculation</title>
  <meta charset="utf-8">
  <meta name="description" content="Server Malfunction Rate Calculation">
  <meta name="author" content="Liang Dong">
  <meta name="generator" content="slidify" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/default.css" media="all" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/phone.css" 
    media="only screen and (max-device-width: 480px)" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/slidify.css" >
  <link rel="stylesheet" href="libraries/highlighters/highlight.js/css/tomorrow.css" />
  <base target="_blank"> <!-- This amazingness opens all links in a new tab. -->  <link rel=stylesheet href="./assets/css/ribbons.css"></link>

  
  <!-- Grab CDN jQuery, fall back to local if offline -->
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>
  <script>window.jQuery || document.write('<script src="libraries/widgets/quiz/js/jquery.js"><\/script>')</script> 
  <script data-main="libraries/frameworks/io2012/js/slides" 
    src="libraries/frameworks/io2012/js/require-1.0.8.min.js">
  </script>
  
  

</head>
<body style="opacity: 0">
  <slides class="layout-widescreen">
    
    <!-- LOGO SLIDE -->
        <slide class="title-slide segue nobackground">
  <hgroup class="auto-fadein">
    <h1>Server Malfunction Rate Calculation</h1>
    <h2></h2>
    <p>Liang Dong<br/>System Administrator</p>
  </hgroup>
  <article></article>  
</slide>
    

    <!-- SLIDES -->
    <slide class="" id="slide-1" style="background:;">
  <hgroup>
    <h2>Introduction</h2>
  </hgroup>
  <article data-timings="">
    <h3>Server Malfunction Rate Prediction</h3>

<p>The Debian servers installed with Open vSwtich Version 2.4.0 has some bugs interconnect to the Cisco Switch configured with keepalive message. Every 10 second, the Cisco Switch will dispatch a keepalive message to the server. The server ethernet port uplink will be malfunctioned (err-disable) by Cisco Switch if the bug has happened.</p>

<p>The incident logs show there are 8 malfunction records in 22204800 keepalive message received on Debian servers.</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="class" id="id" style="background:;">
  <hgroup>
    <h2>Assumption</h2>
  </hgroup>
  <article data-timings="">
    <p>Let&#39;s assuming that:</p>

<ul>
<li><p>The keepalive message recieved on servers and malfunction events are iid (independent identically-distributed)</p></li>
<li><p>Server malfunction rate is constant, and it is proportional to keepalive message events.</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="class" id="id" style="background:;">
  <hgroup>
    <h2>Poisson Distribution</h2>
  </hgroup>
  <article data-timings="">
    <p>Then the malfunction follow the Poisson distribution, which we can calculate the malfunction rate base on the Poisson distribution.</p>

<p>\[P = \frac{\lambda^ke^-k}{k!}\]</p>

<p>The global variables are initialized as follow:</p>

<pre><code class="r">HOURS &lt;- 24
MIN &lt;- 60
SEC &lt;- 60
INCIDENT &lt;- 8
KEEPALIVE_EVENT &lt;- 22204800
lambda &lt;-  INCIDENT/KEEPALIVE_EVENT * (HOURS * MIN * SEC/10)
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="class" id="id" style="background:;">
  <hgroup>
    <h2>Malfunction Rate Calculation</h2>
  </hgroup>
  <article data-timings="">
    <p>The incident rate of 50 servers in 30 days could be caculated:</p>

<pre><code class="r">zero_rate &lt;- ppois(1, lambda*servers*days) - dpois(1, lambda*servers*days)
zero_rate
</code></pre>

<pre><code>## [1] 0.009379201
</code></pre>

<pre><code class="r">once_rate &lt;- dpois(1, lambda*servers*days)
once_rate
</code></pre>

<pre><code>## [1] 0.04379393
</code></pre>

<pre><code class="r">err_rate &lt;- 1 - zero_rate
err_rate
</code></pre>

<pre><code>## [1] 0.9906208
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="class" id="id" style="background:;">
  <hgroup>
    <h2>Conclusion</h2>
  </hgroup>
  <article data-timings="">
    <p>So the rate for one malfunction of 50 servers in 30 days is 0.0437939, rate for no malfunction is 0.0093792, and the rate for one or more malfunction is 0.9906208. The PDF is plotted as follow:</p>

<p><img src="assets/fig/unnamed-chunk-6-1.png" alt="plot of chunk unnamed-chunk-6"></p>

  </article>
  <!-- Presenter Notes -->
</slide>

    <slide class="backdrop"></slide>
  </slides>
  <div class="pagination pagination-small" id='io2012-ptoc' style="display:none;">
    <ul>
      <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=1 title='Introduction'>
         1
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=2 title='Assumption'>
         2
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=3 title='Poisson Distribution'>
         3
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=4 title='Malfunction Rate Calculation'>
         4
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=5 title='Conclusion'>
         5
      </a>
    </li>
  </ul>
  </div>  <!--[if IE]>
    <script 
      src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js">  
    </script>
    <script>CFInstall.check({mode: 'overlay'});</script>
  <![endif]-->
</body>
  <!-- Load Javascripts for Widgets -->
  
  <!-- MathJax: Fall back to local if CDN offline but local image fonts are not supported (saves >100MB) -->
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        processEscapes: true
      }
    });
  </script>
  <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <!-- <script src="https://c328740.ssl.cf1.rackcdn.com/mathjax/2.0-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script> -->
  <script>window.MathJax || document.write('<script type="text/x-mathjax-config">MathJax.Hub.Config({"HTML-CSS":{imageFont:null}});<\/script><script src="libraries/widgets/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"><\/script>')
</script>
<!-- LOAD HIGHLIGHTER JS FILES -->
  <script src="libraries/highlighters/highlight.js/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <!-- DONE LOADING HIGHLIGHTER JS FILES -->
   
  </html>